### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nignatiadis** [julian-gehring/MultipleTesting.jl#10]
Here is a quite comprehensive list of features which covers a big chunk of what is out there in regards to multiple testing. I am not sure which of these are within the scope of the package (or if everything is), but maybe it is a starting point. This also brings up the point regarding what and how many dependencies we will eventually bring in  (e.g. I think Distributions.jl and GLM.jl or so will be unavoidable eventually). I will add references later.

- [ ] More p.adjust procedures (to at least get feature parity with MUTOSS)
- [ ] Additional pi0 estimators (Issue #3)
- [ ] More general interface for multiple testing procedures which don't have equivalent formulation in terms of adjusted pvalues
- [ ] Control methods for  other error rates, such as: 
     - [ ] False Discovery Exceedance (False discovery proportion)
     - [ ] k-FWER
     - [ ]  k-FDR
     - [ ]  PenalizedFDR
- [ ] Standard collection of simulations for benchmarking 
    - [ ] Worst case situations for different procedures  
    - [ ] Beta uniform 
    - [ ] Discrete cases
    - [ ] Different correlation/dependence structures
- [ ] Tests of global null hypothesis
    - [ ] Simes
    - [ ] Fisher combination
- [ ] Higher criticism
- [ ] Weighted hypothesis testing
- [ ] Grouped / Stratified hypotheses
    - [ ] Group BH
    - [ ]  Stratified BH
    - [ ] p-filter
- [ ] local fdr/ tail FDR estimation and interface
- [ ] empirical null modelling
- [ ] Diagnostic or explanatory plots
- [ ] Approaches which start from table like for microarrays
     - [ ] Procedures which model and account for correlation
     - [ ] permutation/resampling/bootstrap based multiple testing approaches
- [ ] Approaches for regression (will need dependencies like Lasso.jl/LARS.jl or GLMNet.jl->
 Probably should be a different package)
     - [ ] Knockoff filters 
- [ ] Old school methods
     - [ ] Tukey's honest significant difference

**Comment by juliangehring** [comment]
What approaches would we want to "finish" no. 1 on the list: 'More p.adjust procedures'?
