### ISSUE TITLE
pi0 estimators roadmap/ideas

### ISSUE THREAD

**Issue by nignatiadis** [julian-gehring/MultipleTesting.jl#3]
Below is a collection of interesting pi0 estimators, which have not been implemented yet. This could also be a good exercise for anyone that would like to contribute!

- [ ] ConvexDecreasing (Langaas, 2005), pi0 estimate based on decreasing convex density fit , available in limma
- [ ] FlatGrenander (Langaas, 2005) pi0 estimate based on longest constant stretch of Grenander estimator (don't know of R implementation)
- [ ] Cross-validation (leave p-out) based pi0 estimator (Celisse and Robin, 2010) Matlab implementation on http://math.univ-lille1.fr/~celisse/
- [ ] CensoredBetaUniform  (Markitsis, 2010) , R implementation function CBUM in package pi0
- [ ] Central Matching, Empirical Null modeling ala Efron where pi0 is fit jointly with the null parameters
- [ ] Restricted MLE Empirical Null modelling, implementation of this or the above would also allow us to provide empirical null functionality
- [ ] A pi0 estimator for discrete p-values, e.g. http://arxiv.org/pdf/1410.4274v1.pdf available in fdrDiscreteNull R package
- [ ] Estimators in http://arxiv.org/pdf/1204.5488v5.pdf ( implementation: http://stat.columbia.edu/~rohit/Code/NPMixModelCode.pdf )

**Comment by julian-gehring** [comment]
Since all R implementations in this list are licensed under GPL, would it be helpful to reconsider the license of the `MultipleTesting` package? Not that I'm a great fan of it, but having it under GPL could avoid a lot of working having to write everything from scratch.
